FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY sync_api ./sync_api
COPY rossmann_sync_schemas ./rossmann_sync_schemas
COPY rossmann_oltp ./rossmann_oltp
COPY rossmann_oltp_models ./rossmann_oltp_models

ENV PYTHONPATH=/app

CMD ["uvicorn", "sync_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]