services:
  db:
    container_name: oltp_db
    image: postgres:latest
    restart: always
    ports:
      - 2001:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    container_name: oltp_adminer
    depends_on:
      db:
        condition: service_healthy
    image: adminer
    restart: always
    ports:
      - 2000:8080

  app:
    container_name: oltp_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

