FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY kafka_consumer ./kafka_consumer
COPY rossmann_oltp ./rossmann_oltp
COPY rossmann_oltp_models ./rossmann_oltp_models

ENV PYTHONPATH=/app

CMD ["python", "-u", "kafka_consumer/consumer.py"]